name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache downloaded documents
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/towndex-etl
          key: ${{ runner.os }}-
      - uses: towndex/gui-action@v1-beta
        with:
          input: ./documents
          output: ./.github/pages
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.github/pages
